version: '3.9'

volumes:
#  front_build:
  database_data:
  static_files:

networks:
  local_area:
    driver: bridge

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    networks:
      local_area:
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      DB_USER: postgres
      DB_PASS: 123
      DB_NAME: mdhh
    expose:
      - "5432"


  backend:
    build:
      context: ../mdhh_ht_backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      local_area:
    restart: unless-stopped
    environment:
      DB_PASS: 123
      DB_USER: postgres
      DB_NAME: mdhh
      DB_HOST: postgres
      DB_PORT: 5432

    depends_on:
      postgres:
        condition: service_started
